dist: trusty
sudo: false

matrix:
    include:
        -   language: node_js
            node_js:
              - '10'
        - dotnet: 2.1.502
          language: csharp
          mono: none

cache:
    directories:
        - frontend/node_modules

script:
    - bash build.sh
notifications:
    email: false
