dist: trusty
sudo: false

matrix:
    include:
        -   language: node_js
            node_js:
              - '10'

cache:
    directories:
        - frontend/node_modules

script:
    - bash build.sh
notifications:
    email: false

