dist: trusty
sudo: false
addons:
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable
matrix:
    include:
        - language: node_js
          node_js:
              - '10'
cache:
    directories:
        - frontend/node_modules
script:
    - bash build.sh
notifications:
    email: false

